#version: '3'
#volumes:
#  dados:
#networks:
#  banco:  
#services: 
#  db:
#    image: postgres:latest    
#    container_name: postgres
#   # volumes:          
#    #  - dados:/var/lib/postgresql/data
#    expose: 
#      - 5432
#    ports:  
#      - 5432:5432
#    environment:
#         - POSTGRES_PASSWORD=postgres
#         - POSTGRES_USER=postgres
#         - POSTGRES_DB=testdb
#    restart: unless-stopped
# # APP*****************************************
#  backend:   
#    image: testedocker:latest
#    network_mode: bridge
#    container_name: testedocker
#    expose: 
#      - 8080
#    ports:  
#      - 8080:9005
#    environment:
#      - DB_NAME=postgres
#    restart: unless-stopped
#    depends_on:
#      - db
#    links:
#      - db
#volumes:
#  postgres-data:
#


version: '3'
volumes:
  dados:
networks:
  banco:  
services:
  db:
    image: postgres:latest  
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockercrud:latest
    container_name: dockercrud
    expose: 
      - 8080
    ports:  
      - 8080:9005    
    networks:
      - banco     
    depends_on:
      - db     
    environment:
      - DB_NAME=postgres 
  