version: '3'
volumes:
  dados:
networks:
  banco:  
services:
  db:
    image: postgres:latest
    container_name: dockerdb
    expose: 
      - 5555
    ports:  
     - 5555:5432
    environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres         
    restart: unless-stopped
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockercrud:latest
    container_name: docker_crud
    expose: 
      - 8080
    ports:  
      - 8080:9005    
    networks:
      - banco     
    depends_on:
      - db     
    environment:
      - DB_NAME=postgres 
    tty: true  