spring:  
  datasource:
    url: jdbc:postgresql://localhost:5555/projetodb
    username: postgres
    password: postgres
  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    show-sql: true
    hibernate:
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
    properties:
      hibernate:
        enable-lazy-load-no-trans: true
        show-sql: true
        temp:
          use_jdbc_metadata_defaults: false
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes : localhost:9300
      cluster-name: elasticsearch
  main:
     allow-bean-definition-overriding: true
server:
  port: 9005
  application:
    name: DockerElastic
  
# Local Elasticsearch config
elasticsearch:
  index:
    name: user_index
  user:
    type: user
